In [15]:
"""
Notebook for unorganized tests and development
"""
import pandas as pd
import numpy as np

test for data processing: parsing numpy.array which are stored as strings

In [11]:
df_ = pd.read_csv('./data/bert_embeddings/all.tsv', sep='\t', names=['label','embed'])

In [25]:
def parse_single_string(string, seq_length=32):
    """
    this function parse a string of elements into np.array
    the string ofthe array might contain [], and should be a 2d matrix
    each row of the array represents a row vector
    also completes the sequence padding job,
    which including cutting the longer sequences, 
    and padding the shorter ones with np.zeros, with the same width as the row vectors
    :param string: str,string of the numpy array
    :param seq_length: int; max sequence length
    :return: a np.ndarray
    """
    arrays = []
    for line in string.split('\n'):
        line = line.replace('[','')
        line = line.replace(']','')
        elements = line.split(' *')
        print(elements)
        arrays.append(np.array(line))
    sentence = np.concatenate(arrays)
    return sentence

In [19]:
print(type(df_['embed'][0]))
print(df_['embed'][0])
example_str = df_['embed'][0]
lines = list(example_str.split('\n'))
print(len(lines))

<class 'str'>
[[ 0.261803  0.157048  0.193782 ... -0.195094  0.545932  0.377449]
 [-0.301234 -0.18264   0.174642 ... -0.681987  0.981235  0.078662]
 [ 0.455625  0.06644  -0.155926 ... -0.375778  0.795304 -0.331886]
 ...
 [ 0.328007  0.110555  0.494772 ... -0.45329   0.13253  -0.594115]
 [-0.049046 -0.014252  0.126001 ...  0.048751  0.013901 -1.539837]
 [ 0.729335  0.130939 -0.04916  ... -0.060102 -0.073085 -0.014148]]
7


In [26]:
parse_single_string(example_str)

[' 0.261803  0.157048  0.193782 ... -0.195094  0.545932  0.377449']
[' -0.301234 -0.18264   0.174642 ... -0.681987  0.981235  0.078662']
['  0.455625  0.06644  -0.155926 ... -0.375778  0.795304 -0.331886']
[' ...']
['  0.328007  0.110555  0.494772 ... -0.45329   0.13253  -0.594115']
[' -0.049046 -0.014252  0.126001 ...  0.048751  0.013901 -1.539837']
['  0.729335  0.130939 -0.04916  ... -0.060102 -0.073085 -0.014148']


ValueError: zero-dimensional arrays cannot be concatenated

In [ ]:
# runtest on parse line

In [57]:
# test on saving np arrays
list_ = []
for i in range(3000):
    list_.append(np.random.rand(45,300))
b = np.random.rand(3000,1)
list_.append(np.random.rand(15,3000))

In [41]:
rand_df = pd.DataFrame(data=b, columns=['label'])
rand_df['embed'] = list_

In [42]:
rand_df.sample

<bound method NDFrame.sample of          label                                              embed
0     0.881206  [[0.14258597807457318, 0.3398932565403531, 0.7...
1     0.978222  [[0.5127065449124689, 0.3880318961937964, 0.53...
2     0.381141  [[0.8180352028784841, 0.04184509770233047, 0.6...
3     0.262677  [[0.45821443213085045, 0.9457486863379397, 0.3...
4     0.212208  [[0.5692408168214886, 0.9383073219873619, 0.21...
...        ...                                                ...
2995  0.654202  [[0.31558634181141143, 0.9197204933430404, 0.8...
2996  0.604534  [[0.2897502711426231, 0.9843839747468621, 0.19...
2997  0.843040  [[0.23897792417188457, 0.48438540964882326, 0....
2998  0.678079  [[0.5356248696065049, 0.38223679941077704, 0.3...
2999  0.230218  [[0.661490107586339, 0.29979165455466483, 0.52...

[3000 rows x 2 columns]>

In [50]:
currentembed = rand_df.iloc[0]['embed']
rand_df.to_csv('./data/test.tsv', sep='\t', index=False, header=False)

In [60]:
np.save('./data/savednumpy.npy',np.array(list_))

In [95]:
c = np.load('./data/savednumpy.npy', allow_pickle=True)

In [96]:
c.shape

(3001,)

In [98]:
cc = np.zeros([3001,1])

In [100]:
df = pd.DataFrame(cc,columns=['name'])

In [104]:
df['embed'] = c

In [105]:
df

name                                              embed
0      0.0  [[0.062049207299212816, 0.26740232153252086, 0...
1      0.0  [[0.7884897113426664, 0.4937040004921027, 0.69...
2      0.0  [[0.706820480080235, 0.29293511200010425, 0.78...
3      0.0  [[0.8336800605178872, 0.28628690590495454, 0.7...
4      0.0  [[0.7600975656980811, 0.9841442128373754, 0.44...
...    ...                                                ...
2996   0.0  [[0.49798005830647474, 0.9660226696070474, 0.4...
2997   0.0  [[0.8366155628466649, 0.8133959452401552, 0.73...
2998   0.0  [[0.6234929237338517, 0.8638718770503728, 0.29...
2999   0.0  [[0.42841396746720517, 0.6534219693696393, 0.1...
3000   0.0  [[0.24552660195493947, 0.8841342034821729, 0.7...

[3001 rows x 2 columns]

In [106]:
df = None
c = None
cc = None

In [125]:
cc = ['a','b','c']
df = pd.DataFrame(cc,columns=['name'])

In [126]:
df

name
0    a
1    b
2    c

In [127]:
dum = pd.get_dummies(df['name']).values
dum_ = []
for i in range(dum.shape[0]):
    dum_.append(dum[i,:])
df['name'] = dum_

In [128]:
df

name
0  [1, 0, 0]
1  [0, 1, 0]
2  [0, 0, 1]

In [129]:
dum

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [130]:
pd.get_dummies(df['name'])

TypeError: unhashable type: 'numpy.ndarray'